language: python
python:
  - 3.6
services:
  - docker
install:
  - docker build -t max-audio-classifier .
  - docker run -it -d -p 5000:5000 max-audio-classifier
  - pip install -r requirements-test.txt
before_script:
  - flake8 . --max-line-length=127
  - bandit -r .
  - sleep 30
script:
  - pytest tests/test.py
