language: python

python:
  - 3.7

services:
  - docker

before_install:
  # Replace all slashes (which are common in branch names) in VERSION with dashes for Docker compatibility
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      VERSION=latest;
    else
      VERSION=${TRAVIS_BRANCH//\//-};
    fi

  # Default variables (used by Jenkins)
  - '[[ -z "$DOCKERFILE" ]] && export DOCKERFILE=Dockerfile || /bin/true'
  - '[[ -z "$IMAGE" ]] && export IMAGE=test || /bin/true'
  - '[[ -z "$ARCH" ]] && export ARCH=x86_64 || /bin/true'
  - '[[ -z "$VERSION" ]] && export VERSION=jenkins || /bin/true'

install:
  - docker build -f "$DOCKERFILE" -t codait/max-audio-classifier:"$IMAGE"-"$ARCH"-"$VERSION" .
  - docker run --rm -p 5000:5000 codait/max-audio-classifier:"$IMAGE"-"$ARCH"-"$VERSION"
  - pip install -r requirements-test.txt

before_script:
  - flake8 . --max-line-length=127
  - bandit -r .
  - sleep 30

script:
  - pytest tests/test.py

after_success:
  - if [[ "$IMAGE" != "test" && "$TRAVIS_PULL_REQUEST" == "false" ]] && [[ "$TRAVIS_BRANCH" == "master" || "$TRAVIS_BRANCH" == "$TRAVIS_TAG" ]]; then
      echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin;
      docker push codait/max-audio-classifier:"$IMAGE"-"$ARCH"-"$VERSION";
    fi

matrix:
  include:
  - os: linux
    env: DOCKERFILE=Dockerfile IMAGE=test ARCH=x86_64
  - os: linux
    arch: arm64
    env: DOCKERFILE=Dockerfile.arm32v7 IMAGE=arm ARCH=arm32v7
